import {
  Code2,
  LineChart,
  Database,
  PenTool,
  Shield,
  HeartPulse,
  ClipboardList,
  Calculator,
  TrendingUp,
  Megaphone,
  Palette,
  Cog,
  Scale,
  GraduationCap,
  Wrench,
  Sparkles,
  Briefcase,
  Stethoscope,
  Pill,
  Dumbbell,
  PawPrint,
  Brain,
  BrainCircuit,
  Globe,
  Server,
  Gamepad2,
  Package,
  Kanban,
  Users,
  Presentation,
  Home,
  Sigma,
  HardHat,
  Zap,
  Rocket,
  Microscope,
  Ruler,
  Sofa,
  Newspaper,
  Clapperboard,
  Camera,
  Gavel,
  Siren,
  HeartHandshake,
  Droplets,
  Fan,
  ChefHat,
  Plane,
  type LucideIcon,
} from 'lucide-react'
import type { CareerCategory } from '../data/types'

const BY_KEY: Record<string, LucideIcon> = {
  'software-developer': Code2,
  'data-analyst': LineChart,
  'data-scientist': Database,
  'ux-designer': PenTool,
  'cybersecurity-analyst': Shield,
  'registered-nurse': HeartPulse,
  'healthcare-coordinator': ClipboardList,
  'accountant-auditor': Calculator,
  'financial-analyst': TrendingUp,
  'creator-strategist': Megaphone,
  'graphic-designer': Palette,
  'mechanical-engineer': Cog,
  'paralegal': Scale,
  'teacher-k12': GraduationCap,
  'electrician': Wrench,
  // Expanded top-50
  'physician': Stethoscope,
  'dentist': Stethoscope,
  'pharmacist': Pill,
  'physical-therapist': Dumbbell,
  'physician-assistant': Stethoscope,
  'nurse-practitioner': HeartPulse,
  'veterinarian': PawPrint,
  'psychologist': Brain,
  'web-developer': Globe,
  'devops-engineer': Server,
  'ml-engineer': BrainCircuit,
  'game-developer': Gamepad2,
  'product-manager': Package,
  'marketing-manager': Megaphone,
  'project-manager': Kanban,
  'hr-specialist': Users,
  'management-consultant': Presentation,
  'real-estate-agent': Home,
  'actuary': Sigma,
  'civil-engineer': HardHat,
  'electrical-engineer': Zap,
  'aerospace-engineer': Rocket,
  'biomedical-engineer': Microscope,
  'architect': Ruler,
  'interior-designer': Sofa,
  'journalist': Newspaper,
  'video-editor': Clapperboard,
  'photographer': Camera,
  'lawyer': Gavel,
  'police-officer': Siren,
  'social-worker': HeartHandshake,
  'plumber': Droplets,
  'hvac-technician': Fan,
  'chef': ChefHat,
  'commercial-pilot': Plane,
}

const BY_CATEGORY: Record<CareerCategory, LucideIcon> = {
  Technology: Code2,
  Healthcare: HeartPulse,
  'Business & Finance': Calculator,
  'Creative & Media': Palette,
  Engineering: Cog,
  Legal: Scale,
  Education: GraduationCap,
  'Skilled Trades': Wrench,
  Other: Briefcase,
}

export function careerIcon(key: string, category: CareerCategory, generated?: boolean): LucideIcon {
  if (generated) return Sparkles
  return BY_KEY[key] ?? BY_CATEGORY[category] ?? Briefcase
}

export function categoryIcon(category: CareerCategory): LucideIcon {
  return BY_CATEGORY[category] ?? Briefcase
}
